name: Create a PR when merged to develop
on:
  pull_request:
    types:
      - closed
    branches:
      - 'develop'
jobs:
  action-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create the Pull Request
        if: github.event.pull_request.merged == true
        id: create_pr
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ github.event.pull_request.title }}
          assignee: ${{ github.actor }}
          get_diff: true
          target_branch: master
          source_branch: develop
          template: ".github/AUTOMATIC_PULL_REQUEST_TEMPLATE.md"
          ignore_users: "dependabot"
          allow_no_diff: false
